jobs:
  update_release_draft:
    name: Update draft release notes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Update draft release notes
      uses: release-drafter/release-drafter@v5
      with:
        config-name: draft-release-notes-config.yml
        tag: (None)
        version: 1.13.0.0
name: Release Drafter
on:
  repository_dispatch:
    types: trigger-ga___draft-release-notes-workflow.yml
