jobs:
  upload-jdbc-jar:
    defaults:
      run:
        working-directory: sql-jdbc
    name: Upload Jar to Maven
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: us-east-1
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '10'
    - continue-on-error: true
      env:
        passphrase: ${{ secrets.PASSPHRASE }}
      name: Upload jdbc Jar to Maven
      run: 'cd ..

        export JAVA10_HOME=$JAVA_HOME

        aws s3 cp s3://opendistro-docs/github-actions/pgp-public-key .

        aws s3 cp s3://opendistro-docs/github-actions/pgp-private-key .


        gpg --import pgp-public-key

        gpg --allow-secret-key-import --import pgp-private-key



        mkdir /home/runner/.gradle

        aws s3 cp s3://opendistro-docs/github-actions/gradle.properties /home/runner/.gradle/

        cd sql-jdbc

        ./gradlew publishShadowPublicationToSonatype-stagingRepository -Dcompiler.java=10
        -Dbuild.snapshot=false -Djavax.net.ssl.trustStore=$JAVA_HOME/lib/security/cacerts

        '
name: Upload sql-jdbc Jar to Maven
on:
  repository_dispatch:
    types: trigger-ga___sql-jdbc-push-jdbc-maven.yml
