jobs:
  Release-SQL-JDBC:
    defaults:
      run:
        working-directory: sql-jdbc
    name: Build and Release JDBC Plugin
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout SQL-JDBC
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: us-east-1
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Run build
      run: './gradlew publishShadowPublicationToInternal-releasesRepository ''-Dorg.gradle.jvmargs=--add-modules
        java.xml.bind'' -Dbuild.snapshot=false

        '
    - continue-on-error: true
      name: Configure Staging AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
        aws-region: us-east-1
        aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      name: Publish to S3
      run: 'jar=`ls -1t build/libs/*.jar | grep -v "SNAPSHOT.jar" | grep -v "sources.jar"
        | head -1`


        # Inject the build number before the suffix

        jar_outfile=`basename ${jar%.jar}-build-${GITHUB_RUN_NUMBER}.jar`


        s3_prefix="s3://staging.artifacts.opendistroforelasticsearch.amazon.com/snapshots/elasticsearch-clients/sql-jdbc/"


        echo "Copying ${jar} to ${s3_prefix}${jar_outfile}"

        aws s3 cp --quiet $jar ${s3_prefix}${jar_outfile}

        '
      shell: bash
    strategy:
      matrix:
        java:
        - 10
name: Build and Release SQL-JDBC
on:
  repository_dispatch:
    types: trigger-ga___sql-jdbc-release-workflow.yml
