jobs:
  build:
    defaults:
      run:
        working-directory: sql-cli
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout SQL CLI
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - continue-on-error: true
      name: Install Python Dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements-dev.txt

        pip install setuptools wheel

        '
    - continue-on-error: true
      name: Set up ES and install SQL plugin
      run: 'sudo add-apt-repository ppa:openjdk-r/ppa

        sudo apt update

        sudo apt install openjdk-13-jdk

        sudo apt install unzip

        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.10.0-amd64.deb

        sudo dpkg -i elasticsearch-oss-7.10.0-amd64.deb

        sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-sql/opendistro_sql-1.12.0.0.zip

        sudo systemctl start elasticsearch.service

        '
    - continue-on-error: true
      name: Run Tox Testing
      run: tox
    - continue-on-error: true
      name: Stop ES
      run: sudo systemctl stop elasticsearch.service
    - continue-on-error: true
      name: Build Artifact
      run: python setup.py sdist bdist_wheel
    - continue-on-error: true
      name: Create Artifact Path
      run: 'mkdir -p opendistro-sql-cli-builds

        cp -r ./dist/*.tar.gz ./dist/*.whl opendistro-sql-cli-builds/

        '
    - continue-on-error: true
      name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: opendistro-sql-cli
        path: sql-cli/opendistro-sql-cli-builds
    strategy:
      matrix:
        python-version:
        - 3.8
name: SQL CLI Test and Build
on:
  repository_dispatch:
    types: trigger-ga___sql-cli-test-and-build-workflow.yml
