env:
  OD_VERSION: 1.13.2.0
  PLUGIN_NAME: opendistroQueryWorkbenchKibana
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Plugin
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Checkout Kibana
      uses: actions/checkout@v1
      with:
        path: sql/kibana
        ref: v7.10.2
        repository: elastic/kibana
    - continue-on-error: true
      name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.23.1
    - continue-on-error: true
      name: Move Workbench to Plugins Dir
      run: 'mv workbench kibana/plugins

        '
    - continue-on-error: true
      name: Kibana Plugin Bootstrap
      uses: nick-invision/retry@v1
      with:
        command: cd kibana/plugins/workbench; yarn kbn bootstrap
        max_attempts: 3
        timeout_minutes: 60
    - continue-on-error: true
      name: Test
      run: 'cd kibana/plugins/workbench

        yarn test:jest

        '
    - continue-on-error: true
      name: Build Artifact
      run: 'cd kibana/plugins/workbench

        yarn build

        mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}.zip

        '
    - continue-on-error: true
      name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: workbench
        path: kibana/plugins/workbench/build
name: SQL Workbench Test and Build
on:
  repository_dispatch:
    types: trigger-ga___sql-workbench-test-and-build-workflow.yml
