jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build assemble
    - continue-on-error: true
      name: Create Artifact Path
      run: 'mkdir -p opendistro-sql-builds

        cp -r ./plugin/build/distributions/*.zip opendistro-sql-builds/

        '
    - continue-on-error: true
      name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: opendistro-sql
        path: opendistro-sql-builds
name: SQL Java CI
on:
  repository_dispatch:
    types: trigger-ga___sql-test-and-build-workflow.yml
